name: Bug report
description: File a bug report
labels: [bug]

body:
    - type: markdown
      attributes:
        value: |
          # Bug report
          Thanks for taking the time to file a bug report. Provide as much information as possible to help dev identify and solve the problem.

    - type: input
      id: hydrus_version
      attributes:
        label: Hydrus version
        description: You can find this in the "about" dialog from the "help" menu. Kindly update to the latest version before filing a report.
        placeholder: v447 or just 447 are both acceptable.
      validations:
        required: true
        
    - type: dropdown
      id: qt_version
      attributes:
        label: Qt major version
        description: You can find this in the "about Qt" dialog from the "help" menu.
        options:
          - Qt 6
          - Qt 5
      validations:
        required: true

    - type: dropdown
      id: os
      attributes:
        label: Operating system
        description: What operating system do you use?
        options:
          - Windows 11
          - Windows 10
          - Windows other (specify in comments)
          - macOS 15 "Sequoia" (Apple silicon)
          - macOS 15 "Sequoia" (Intel)
          - macOS 14 "Sonoma" (Apple silicon)
          - macOS 14 "Sonoma" (Intel)
          - macOS 13 "Ventura" (Apple silicon)
          - macOS 13 "Ventura" (Intel)
          - macOS other (specify in comments)
          - Linux (specify distro and version in comments)
          - Other (aka none of the above, specify in the comments)
      validations:
        required: true

    - type: dropdown
      id: install_method
      attributes:
        label: Install method
        description: Which install method did you use?
        options:
          - Installer
          - Extract
          - Running from source
          - Third party (AUR, Docker, Chocolatey, etc. Specify in comments)
      validations:
        required: true

    - type: textarea
      id: os_install
      attributes:
        label: Install and OS comments
        description: Optional comments about OS and installation method

    - type: textarea
      id: bug_description
      attributes:
        label: Bug description and reproduction
        description: Describe your issue in as much detail as you can. When did it happen? How did it happen? Does it keep happening? You can also post relevant text files or images here.
        placeholder: | 
          1. 
          2. 
          3. 
          ...
      validations:
        required: true          

    - type: textarea
      id: logs
      attributes:
        label: Log output
        description: Either copy and paste relevant log sections here or upload the file in the bug description above.
        render: text
