name: Feature Request
description: Suggest an idea for Hydrus
title: "[Feature]: "
labels: ["experimental", "unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        Please check if your feature request hasn't been suggested before.
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: A clear and concise description of what the feature is.
      placeholder: I would like to see...
    validations:
      required: true
  - type: textarea
    id: problem-solved
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: It's frustrating when...
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
