# -- What this file is --

# This .conf tells mpv in hydrus how to load. If you have no "mpv.conf" in your db directory (for instance on first start), the file at install_dir/(lib/)static/mpv-conf/default_mpv.conf is copied into place.

# You can add to or edit an option in this file in your db folder any time and then open/save the options dialog, and the changes should take effect. If you need to remove an option, restart the client.

# The full specification for mpv options is here: https://mpv.io/manual/master/ . This is a big and complicated document, so I recommend talking with a chatbot to help diagnose and fix any particular problem.

# If you have mpv installed and available in your PATH, these terminal commands can help:

# mpv --hwdec=help
# mpv --vo=help
# mpv --gpu-api=help

# These three options are different and overlapping parts of the general rendering system. The defaults are generall 'let mpv figure it out', which generally works great, but if you have flickering, black screens, GPU driver issues, they are your first stop.

# Note that hydrus embeds the mpv window in a hacky way, and I override some event handling; I recommend against attempting to enable the OSD or other mpv-specific mouse/keyboard interactions.



# -- Settings --

# -- Fast Directory Handling --

# these are very important if hydrus has a large file collection, particularly over SMB,
# since mpv often wants to scan the media file's directory for subtitles and so on--we don't want to do that on a dir with 20k items every time we load a file

autoload-files=no
access-references=no
rescan-external-files=keep-selection

# -- Embedding Images For Audio Files --

audio-display=embedded-first

# -- Mouse Autohide --

# Some OSes immediately hide the mouse cursor, so let's defer to hydrus proper

cursor-autohide=no



# -- User Settings --

# I recommend you add new stuff here




# -- Experiments --

# Feel free to play around with these, but they are advanced and generally have to be fit to a particular system and sometimes break with a new driver version.
# If anything goes nuts with this stuff, just comment it back out and restart the client.

# -- Audio Normalisation Experiments --

# The following seems to work for audio normalisation, but it needs to scan the whole file and thus can introduce load/loop CPU lag that hits particularly hard when transitioning media near the end of the current media
# it could also cause pops, crackles, or sudden system-wide audio silences on Linux!
# This may help: https://ffmpeg.org/ffmpeg-filters.html

# af=lavfi=[loudnorm=I=-16:TP=-3:LRA=4]

# this is truly dynamic (f value is the number of previous milliseconds it bases its normalisation on) and may work better for you

# af=lavfi=[dynaudnorm=g=3:f=1000:r=0.9:p=0.9:m=10]

# Another, simpler variant:

# # af=lavfi=[dynaudnorm=p=0.9]

# -- High Quality Video Experiments --

# mostly from here: https://wiki.archlinux.org/index.php/Mpv

# profile=gpu-hq
# scale=ewa_lanczossharp
# cscale=ewa_lanczossharp
# video-sync=display-resample
# interpolation
# tscale=oversample

# enable hardware acceleration
# may improve performance, may cause errors
# you may find hwdec=auto-copy looks better/smoother for you

# hwdec=auto
# hwdec-codecs=all

# needed for SVP

# input-ipc-server=mpvpipe