.open client.db
ATTACH "client.caches.db" as external_caches;
ATTACH "client.master.db" as external_master;
ATTACH "client.mappings.db" as external_mappings;
.print ''
.print '   r::::::::::::::::::::::::::::::::::r'
.print '   :                                  :'
.print '   :               :PP.               :'
.print '   :               vBBr               :'
.print '   :               7BB:               :'
.print '   :               rBB:               :'
.print '   :      :DQRE:   rBB:   :gMBb:      :'
.print '   :       :BBBi   rBB:   7BBB.       :'
.print '   :        KBB:   rBB:   rBBI        :'
.print '   :        qBB:   rBB:   rQBU        :'
.print '   :        qBB:   rBB:   iBBS        :'
.print '   :        qBB:   iBB:   7BBj        :'
.print '   :        iBBY   iBB.   2BB.        :'
.print '   :         SBQq  iBQ:  EBBY         :'
.print '   :          :MQBZMBBDRBBP.          :'
.print '   :              .YBB7               :'
.print '   :               :BB.               :'
.print '   :               7BBi               :'
.print '   :               rBB:               :'
.print '   :                                  :'
.print '   r::::::::::::::::::::::::::::::::::r'
.print ''
.print 'Remember to use ".exit" to cleanly exit the session.'
.print ''