class CantRenderWithCVException( Exception ): pass
class DBException( Exception ): pass
class DBAccessException( Exception ): pass
class FileException( Exception ): pass
class MimeException( Exception ): pass
class NameException( Exception ): pass
class NotFoundException( Exception ): pass
class PermissionException( Exception ): pass
class ShutdownException( Exception ): pass
class SizeException( Exception ): pass

class NetworkException( Exception ): pass
class FirewallException( NetworkException ): pass
class ForbiddenException( NetworkException ): pass
class NetworkVersionException( NetworkException ): pass
class NoContentException( NetworkException ): pass
class NotModifiedException( NetworkException ): pass
class ServerBusyException( NetworkException ): pass
class SessionException( NetworkException ): pass
class WrongServiceTypeException( NetworkException ): pass