class DBException( Exception ): pass
class DBAccessException( Exception ): pass
class MimeException( Exception ): pass
class SizeException( Exception ): pass
class NetworkVersionException( Exception ): pass
class NoContentException( Exception ): pass
class NotFoundException( Exception ): pass
class NotModifiedException( Exception ): pass
class ForbiddenException( Exception ): pass
class PermissionException( Exception ): pass
class SessionException( Exception ): pass
class ShutdownException( Exception ): pass
class WrongServiceTypeException( Exception ): pass
