name: Release-Windows
on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      -
        name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          path: hydrus
      -
        name: Extract Version Metadata
        id: meta
        run: |
          $vs = "${{ github.ref_name }}".Substring(1)
          echo "version_short=$vs" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      -
        name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: '3.13'
          architecture: x64
      -
        name: Pip Install
        run: |
          cd hydrus
          python3 -m pip install .
          python3 -m pip install pefile
          python3 -m pip install pyinstaller==6.18.0
          python3 -m pip install mkdocs-material==9.7.1
          cd ..
      - 
        name: Build docs to /help
        run: mkdocs build -d help -f mkdocs-offline.yml
        working-directory: hydrus
      -
        name: Download and Extract mpv-dev
        run: |
          Invoke-WebRequest -Uri "https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-20240818-git-a3baf94.7z" -OutFile "mpv-dev-x86_64.7z" -Headers @{ "User-Agent" = "LetMeIn" }
          7z e mpv-dev-x86_64.7z -ohydrus "libmpv-2.dll"
      -
        name: Download and Extract FFmpeg
        run: |
          Invoke-WebRequest -Uri "https://github.com/GyanD/codexffmpeg/releases/download/8.1.2/ffmpeg-8.1.2-full_build.7z" -OutFile "ffmpeg-release-full.7z"
          7z e ffmpeg-release-full.7z -ohydrus/bin "**/bin/ffmpeg.exe"
      -
        name: Build Hydrus
        run: |
          python hydrus\static\build_files\windows\file_version_info_maker.py ${{ github.ref_name }}
          copy hydrus\static\build_files\windows\hydrus.spec hydrus.spec
          pyinstaller hydrus.spec
      -
        name: InnoSetup
        run: |
          copy hydrus\static\build_files\windows\InnoSetup.iss InnoSetup.iss
          ISCC.exe InnoSetup.iss /DVersion=${{ github.ref_name }} /DVersionShort=${{ env.version_short }}
      -
        name: Compress Client
        run: |
          7z a -tzip -mm=Deflate -mx=5 Hydrus.Network.${{ env.version_short }}.-.Windows.-.Extract.only.zip .\dist\*
      -
        name: Upload Files
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Hydrus.Network.${{ env.version_short }}.-.Windows.-.Installer.exe
            Hydrus.Network.${{ env.version_short }}.-.Windows.-.Extract.only.zip
