name: Release-macOS-Intel
on:
  push:
    tags:
      - 'NO-v*'

jobs:
  build-macos:
    runs-on: macos-14
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      -
        name: Build docs to /help
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade wheel
          python3 -m pip install mkdocs-material
          mkdocs build -d help
      -
        name: Install PyOxidizer
        run: python3 -m pip install pyoxidizer==0.24.0
      -
        name: Download ffmpeg
        run: |
          cd $GITHUB_WORKSPACE
          curl -L -o ffmpeg-macos.7z https://evermeet.cx/ffmpeg/getrelease/ffmpeg/7z
      -
        name: Process ffmpeg
        run: |
          cd $GITHUB_WORKSPACE
          7z e ffmpeg-macos.7z -obin "ffmpeg"
      -
        name: Extract Version Metadata
        id: meta
        run: |
          echo "version=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "version_short=${GITHUB_REF##*/v}" >> $GITHUB_ENV
      -
        name: Write version to Info.plist
        run: |
          cd $GITHUB_WORKSPACE
          plutil -replace CFBundleShortVersionString -string "${{ env.version_short }}" static/build_files/macos_intel/Info.plist
      -
        name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'
      -
        name: Build Hydrus
        run: |
          cd $GITHUB_WORKSPACE
          cp static/build_files/macos_intel/pyoxidizer.bzl pyoxidizer.bzl
          cp static/build_files/macos_intel/requirements.txt requirements.txt
          basename $(rustc --print sysroot) | sed -e "s/^stable-//" > triple.txt
          rustup target add x86_64-apple-darwin
          pyoxidizer build --release --target-triple x86_64-apple-darwin
          cd build/$(head -n 1 triple.txt)/release
          mkdir -p "Hydrus Network.app/Contents/MacOS"
          mkdir -p "Hydrus Network.app/Contents/Resources"
          mkdir -p "Hydrus Network.app/Contents/Frameworks"
          mv install/static/icon.icns "Hydrus Network.app/Contents/Resources/icon.icns"
          cp install/static/build_files/macos_intel/Info.plist "Hydrus Network.app/Contents/Info.plist"
          cp install/static/build_files/macos_intel/running_from_app "install/running_from_app"
          mv install/* "Hydrus Network.app/Contents/MacOS/"
          rm -rf install
      -
        name: Zip it up
        run: |
          cd $GITHUB_WORKSPACE
          cd build/$(head -n 1 triple.txt)/release
          zip -r "Hydrus Network.zip" "Hydrus Network.app"
          mv "Hydrus Network.zip" "$GITHUB_WORKSPACE/Hydrus.Network.${{ env.version_short }}.-.macOS.-.App.-.Intel.zip"
          cd $GITHUB_WORKSPACE
      - 
        name: Upload Files
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Hydrus.Network.${{ env.version_short }}.-.macOS.-.App.-.Intel.zip
